In [87]:
import numpy as np
import random
from sklearn.decomposition import PCA

In [88]:
def fill_data(ndata, nfeat, absmax_val, absmax_err, absmax_mult):
    data = np.zeros((ndata, nfeat))
    for j in range(nfeat):
        if j < (nfeat/2):
            for i in range (ndata):
                random.seed()
                data[i][j] = random.uniform(-absmax_val, absmax_val)
        else:
            random.seed()
            mult = random.uniform(-absmax_mult, absmax_mult)
            for i in range (1000):
                random.seed()
                err = random.uniform(-absmax_err, absmax_err)
                data[i][j] = data[i][j-4] * mult + err
    return data

In [89]:
absmax_val = 10
absmax_err = 0.5
absmax_mult = 5
database = fill_data(1000, 10, absmax_val, absmax_err, absmax_mult)

In [90]:
print(database)

[[ -5.56218672   3.74651353  -5.25356645 ...  -7.51015166 -13.56173039
   18.47660516]
 [ -8.96488049  -5.20579556   4.3383639  ...   9.59242913 -13.36555996
  -24.37902345]
 [  6.92056547  -4.81056196   8.1526034  ...   6.40931327  -9.6390775
  -22.86902407]
 ...
 [  2.34140302   1.06855788  -5.07875902 ... -12.9460774  -11.03942237
    5.36495787]
 [  6.11810288  -3.13052182  -8.09125241 ...   5.89951087   6.13712397
  -15.58581062]
 [  9.96488035   2.26377062  -8.93852912 ...  -7.95654771 -23.39116652
   12.48210927]]


In [91]:
pca = PCA(n_components = 5)
reduced_data = pca.fit_transform(database)
print(reduced_data)

[[-18.24969204 -17.98383994 -16.15022215  -6.78734054  -5.27714665]
 [ 25.45247285  19.11188513 -12.68656614  12.33847692  -8.80205708]
 [ 23.24341835  32.62606421  -7.98884087   7.7779666    6.9876505 ]
 ...
 [ -4.51075951 -16.69636979 -13.97505669 -13.65151961   2.45094225]
 [ 18.74229088 -27.08464269   5.02540746   7.80592813   6.49285855]
 [-11.38140552 -29.88068212 -27.72796032  -6.34570745  10.24144254]]


In [92]:
recover = pca.inverse_transform(reduced_data)
print(recover)

[[ -5.56242708   3.85902738  -5.33457256 ...  -7.59425998 -13.59750659
   18.44525632]
 [ -8.96521784  -5.10038215   4.35867064 ...   9.45171792 -13.31212341
  -24.42683287]
 [  6.92056098  -4.78152031   8.27688109 ...   6.39922483  -9.57770271
  -22.88359629]
 ...
 [  2.34182425   1.11971795  -5.08000464 ... -12.78976529 -10.98762527
    5.33964385]
 [  6.11840724  -3.22999107  -8.1075027  ...   6.0167815    6.14275459
  -15.57568345]
 [  9.96506886   2.60401214  -8.99769263 ...  -7.88328583 -23.37145178
   12.42718727]]


In [93]:
def compute_error(database, recover):
    [ndata, nfeat] = database.shape
    error = 0
    for i in range(ndata):
        for j in range(nfeat):
            error = error + abs(database[i][j] - recover[i][j])
    return error/(ndata*nfeat*absmax_val)

In [94]:
error = compute_error(database, recover)
print(error)

0.007074546841001783


In [108]:
cov = pca.get_covariance()
print(cov[0][4])

0.14707620575458907
